application: Bloodless-Angular-Mongo-Todo
version: 1
deploy: true
pub: true
dart2js: true
framework: bloodless 

handlers:
- url: /todos
  script: server.dart

# Static content, will be served by your app's Nginx instance 
- url: /
  match: postregex
  static_dir: web



